baseurl = "https://chaingng.github.io"
title = "Hack Engineering"
languageCode = "ja"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-87677188-2" # Enable Google Analytics by entering your tracking id
hasCJKLanguage = true

[Author]
    name = "Takatomo Honda"
    bio = "システム開発 / プロトタイプ開発 / 開発組織の構築 / アプリケーションの内製化 /等、お気軽にご相談ください。"
    avatar = "img/myicon.jpeg"


[Params]
    # subtitle = "Just another site" # Subtitle of your site
    # description = " John Doe's Personal blog about everything" # Description of your site
    opengraph = true
    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages
    #dateformat = "2006-01-02" # change the format of dates


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 10 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)
    social = true # Enable "Social" widget
    social_facebook = "takatomo.honda"
    social_twitter = "takatm0103"
    social_linkedin = "takatomo-honda-2b7479b0"
    social_github = "chaingng"
    social_email = "takatomo.honda.0103@gmail.com"
